name=AdiWiFiManager
version=1.0.0
author=Adi S
category=Communication
maintainer=Adi S <electroadi.connect@gmail.com>
sentence=WiFi Manager for ESP32 with inbuilt SD and or LittleFS Web File Manager Support.
paragraph=Library does network provisioning, automatically stores upto 5 past WiFi network connection details and automatically deletes the first one in the list when a new one is added. + A WHOLE BUNCH OF OTHER COOL FEATURES.
url=https://github.com/electro-adi/AdiWiFiManager
architectures=esp32
includes=AdiWiFiManager.h